### ISSUE TITLE
A 'hétköznap' kifejezést nem ismeri fel

### ISSUE THREAD

**Issue by matyas-kovacs** [COREtxt/hundate-core#1]
# Tesztesetek, kategóriánként csoportosítva
fn_print('ÖSSZETETT KIFEJEZÉSEK',[
            '2023 második féléve harmadik hetének közepén',         # többszörös beágyazást is értelmez (a példa 4-szeresen beágyazott)
            'jövő karácsony után',
            'február 5. utáni első hétköznap',
            'február 5 utáni első hétköznap',
            'jövő héten kedd-szerda',
            'halottak napja utáni szombat',
            'jövő héten kedd vagy szerda',
            ],bSzegedAI)

input('\nBezárás: enter')
exit()

**Comment by emodyzs** [comment]
Ki lett adva az 1.0.2 verzió, ami kezeli a megadott példákat.
Az ezdate_teszt.py fájlba fel lett véve egy "Issue1" példacsoport, ami tartalmazza a fenti példákat, de a többi példatár is ki lett egészítve a "hétköznap", "hétközben", "munkanap" szavakat tartalmazó példákkal.
A "jövé héten kedd vagy szerda" példához annyi megjegyzés, hogy ebben az esetben két dátumkifejezés az eredmény.
